AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Agent WAF - Serverless Policy-Enforcing Proxy
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME:
          Ref: WafStateTable
Resources:
  WafStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  WafFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        s3://aws-sam-cli-managed-default-samclisourcebucket-xc6eysxdumik/56ff21d1b96d7a05d9506d37e96bdfd2
      Handler: app.main.handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: WafStateTable
    Metadata:
      SamResourceId: WafFunction
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: 
        https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  DynamoDbTableName:
    Description: DynamoDB Table Name
    Value:
      Ref: WafStateTable
